import { OrvilleCast } from '@/types/types'

export const crew: OrvilleCast[] = [
  {
    id: 1,
    name: 'Cmdr. Kelly Grayson',
    avatar: 'KG',
    role: 'First Officer',
    actor: 'Adrianne Palicki',
    bio: 'Kelly Grayson is the First Officer of the Orville. She is a great leader, and is known for her diplomacy and leadership skills. She is a human from planet earth. She lives aboard the Orville.',
    rank: 'Commander',
    department: 'Command',
    species: 'Human',
    homeworld: {
      name: 'Earth',
      image: '/static/images/earth.jpg',
      description:
        'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other evidence, Earth formed over 4.5 billion years ago. Earth’s gravity interacts with other objects in space, especially the Sun and the Moon, Earth’s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as a year. During this time, Earth rotates about its axis about 366.26 times.',
    },
  },
  {
    id: 2,
    name: 'Dr. Claire Finn',
    avatar: 'CF',
    role: 'Chief Medical Officer',
    actor: 'Penny Johnson Jerald',
    bio: 'Dr. Claire Finn is the Chief Medical Officer of the Orville. She is a skilled doctor and scientist, and is known for her quick thinking and leadership skills. She is a human from planet earth. She lives aboard the Orville with her 2 son.',
    rank: 'Doctor',
    department: 'Medical',
    species: 'Human',
    homeworld: {
      name: 'Earth',
      image: '/static/images/earth.jpg',
      description:
        'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other evidence, Earth formed over 4.5 billion years ago. Earth’s gravity interacts with other objects in space, especially the Sun and the Moon, Earth’s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as a year. During this time, Earth rotates about its axis about 366.26 times.',
    },
  },
  {
    id: 3,
    name: 'Lt. Commander Bortus',
    avatar: 'BH',
    role: 'Second Officer',
    actor: 'Peter Macon',
    bio: 'Bortus is a Lt. Commander of the Orville. He is a skilled security officer and leader. He is a moclan from planet moclan. He lives aboard the Orville.',
    rank: 'Commander',
    department: 'Security',
    species: 'Moclan',
    funFacts: [
      'Eats a cactus plant in one bite.',
      'A great singer.',
      'He is a softy on the inside.',
    ],
    homeworld: {
      name: 'Moclus',
      image: '/static/images/exoplanets-could-be-hi.jpg',
      description:
        'Moclan is a planet in the Orville universe. It is a planet that is home to the Moclan people. They are a race of people that are known for their great leaders and their great warriors.',
    },
  },
  {
    id: 4,
    name: 'Lt. Gordon Malloy',
    avatar: 'GM',
    role: 'Helmsman',
    actor: 'Scott Grimes',
    bio: 'Gordon Malloy is a Lieutenant and Pilot of the Orville. He is a skilled pilot and engineer, and is known for his quick thinking and leadership skills.',
    rank: 'Lieutenant',
    department: 'Science',
    species: 'Human',
    funFacts: [
      'Best pilot in the fleet.',
      'Great singer.',
      'Great sense of humor.',
    ],
    homeworld: {
      name: 'Earth',
      image: '/static/images/earth.jpg',
      description:
        'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other evidence, Earth formed over 4.5 billion years ago. Earth’s gravity interacts with other objects in space, especially the Sun and the Moon, Earth’s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as a year. During this time, Earth rotates about its axis about 366.26 times.',
    },
  },
  {
    id: 6,
    name: 'Captain Ed Mercer',
    avatar: 'EM',
    role: 'Captain',
    actor: 'Seth MacFarlane',
    bio: 'Ed Mercer is the Captain of the Orville. He is a skilled pilot and engineer, and is known for his quick thinking and leadership skills.',
    rank: 'Captain',
    department: 'Command',
    species: 'Human',
    homeworld: {
      name: 'Earth',
      image: '/static/images/earth.jpg',
      description:
        'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other evidence, Earth formed over 4.5 billion years ago. Earth’s gravity interacts with other objects in space, especially the Sun and the Moon, Earth’s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as a year. During this time, Earth rotates about its axis about 366.26 times.',
    },
  },
  {
    id: 7,
    name: 'Lt. Alara Kitan',
    avatar: 'AK',
    role: 'Chief of Security',
    actor: 'Halston Sage',
    rank: 'Lieutenant',
    bio: 'Alara Kitan is a Lieutenant and Chief of Security of the Orville. She is a skilled pilot and engineer, and is known for her quick thinking and leadership skills.',
    department: 'Security',
    species: 'Xelayan',
    funFacts: ['Known for her strength.', 'Great fighter'],
    homeworld: {
      name: 'Zaralon',
      image: '/static/images/Science_1-kepler186f-(1).webp',
      description:
        "Zaralon is a mountainous planet with a thin, icy atmosphere and glowing blue rivers that wind through crystalline valleys. Its gravity is slightly higher than Earth's, and its native flora is known for its bioluminescent properties, lighting up the night in vibrant colors.",
    },
  },
  {
    id: 8,
    name: 'Lt. Commander John LaMarr',
    avatar: 'JL',
    role: 'Chief Engineer',
    actor: 'J. Lee',
    bio: 'John LaMarr is a Lieutenant and Chief of Engineering of the Orville. He is a skilled pilot and engineer, and is known for his quick thinking and leadership skills.',
    rank: 'Commander',
    department: 'Engineering',
    species: 'Human',
    funFacts: [
      'Has highest IQ in the fleet.',
      'Great engineer.',
      'Great leader.',
    ],
    homeworld: {
      name: 'Earth',
      image: '/static/images/earth.jpg',
      description:
        'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other evidence, Earth formed over 4.5 billion years ago. Earth’s gravity interacts with other objects in space, especially the Sun and the Moon, Earth’s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as a year. During this time, Earth rotates about its axis about 366.26 times.',
    },
  },
  {
    id: 9,
    name: 'Cmdr. Talla Keyali',
    avatar: 'TK',
    role: 'Chief of Security',
    actor: 'Jessica Szohr',
    bio: 'Talla Keyali is a Commander and Chief of Security of the Orville. She is a skilled pilot and engineer, and is known for her quick thinking and leadership skills.',
    rank: 'Commander',
    department: 'Security',
    species: 'Human',
    funFacts: [
      'Has a pet cat named "Tally".',
      'Loves to cook.',
      'Great at fixing things.',
    ],
    homeworld: {
      name: 'Virellia',
      image: '/static/images/Science_1-kepler186f-(1).webp',
      description:
        'Virellia is a lush, temperate planet known for its sprawling emerald forests and floating mountain ranges. Its atmosphere is rich in oxygen and faintly glows green at dusk. The native Virellians are renowned for their advanced botanical sciences and harmonious relationship with the planet’s unique wildlife.',
    },
  },
  {
    id: 10,
    name: 'Ensign Charly Burke',
    avatar: 'CB',
    role: 'Ensign',
    actor: 'Ann Winter',
    bio: 'Charly Burke is an Ensign of the Orville. She is a skilled pilot and engineer, and is known for her quick thinking and leadership skills.',
    rank: 'Ensign',
    department: 'Engineering',
    species: 'Human',
    homeworld: {
      name: 'Earth',
      image: '/static/images/earth.jpg',
      description:
        'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other evidence, Earth formed over 4.5 billion years ago. Earth’s gravity interacts with other objects in space, especially the Sun and the Moon, Earth’s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as a year. During this time, Earth rotates about its axis about 366.26 times.',
    },
  },
  {
    id: 11,
    name: 'Lt. Yaphit T',
    role: 'Lieutenant',
    actor: 'Norm MacDonald',
    rank: 'Lieutenant',
    department: 'Science',
    species: 'Human',
    avatar: 'YT',
    bio: 'Yaphit is a Lieutenant of the Orville. He is a skilled pilot and engineer, and is known for his quick thinking and leadership skills.',
    homeworld: {
      name: 'Zyphora',
      image: '/static/images/exoplanets1.webp',
      description:
        'Zyphora is a mysterious planet located in the outer rim of the Kaylon sector. Known for its swirling violet storms and floating crystal forests, Zyphora is home to a variety of rare minerals and unique lifeforms. Its atmosphere shimmers with bioluminescent clouds, making its nights as bright as its days.',
    },
  },
]
